import {
  Button,
  Card,
  Container,
  Paper,
  Typography,
  Box,
  Checkbox,
  FormControlLabel,
} from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import Breadcrumb from "../components/Breadcrumb/Breadcrumb";
import { Footer } from "../components/Footer/Footer";
import { Link } from "../components/Link/Link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Project name placeholder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <Container
          sx={{
            height: "100%",
            padding: "100px 0",
          }}
          maxWidth="xl"
        >
          <Typography variant="h1" gutterBottom={true}>
            Project name placeholder
          </Typography>

          <Card
            sx={{
              display: "grid",
            }}
          >
            <Breadcrumb />

            <Box>
              <Link href="/prihlaseni">
                <Button variant="contained">
                  <Typography variant="h2" component="span">
                    Přihlásit
                  </Typography>
                </Button>
              </Link>

              <Link href="/registrace">
                <Button variant="contained">
                  <Typography variant="h2" component="span">
                    Registrovat
                  </Typography>
                </Button>
              </Link>
            </Box>
          </Card>
        </Container>
      </Box>

      {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
    </div>
  );
};

export default Home;
