name: fe.prod Deploy production
on:
  workflow_run:
    workflows: [be.prod Deploy aws cdk]
    types:
      - completed
jobs:
  Deploy-production:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Deploy preview
        run: VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }} VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }} > preview_url.txt
