name: fe.preview Deploy preview
on:
  workflow_run:
    workflows: [be.preview Deploy aws cdk]
    types:
      - completed
jobs:
  deployPreview:
    runs-on: ubuntu-20.04
    outputs:
      previewUrl: ${{ steps.output.outputs.previewUrl }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Deploy preview
        run: VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }} VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} vercel deploy --yes --token ${{ secrets.VERCEL_TOKEN }} > preview_url.txt

      - name: Set deployed preview url to env to be used as host in tests
        run: echo "HOST_URL=$(cat preview_url.txt)" >> $GITHUB_ENV

      - id: output
        name: Set job output
        run: echo "previewUrl=${{ env.HOST_URL }}" >> $GITHUB_OUTPUT

      - name: Log HOST_URL
        run: echo "HOST_URL env is ${{ env.HOST_URL }}"

  runE2e:
    runs-on: ubuntu-20.04
    needs: [deployPreview]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install ./frontend node modules
        run: cd ./frontend && npm ci

      - name: Install playwright
        run: cd ./frontend && npx playwright install && npx playwright install-deps

      - name: Run e2e tests
        run: cd ./frontend && HOST_URL=${{ needs.deployPreview.outputs.previewUrl }} npm run e2e:ci

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./frontend/playwright-report
